# Generated by Django 6.0.7 on 2026-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('path_archivo', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'comprobantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('completada', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministradorConsorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('nombre', models.TextField()),
                ('fecha_inscripcion', models.DateField()),
                ('oneroso', models.CharField(max_length=10)),
                ('correo', models.TextField(blank=True, null=True)),
                ('sanciones', models.TextField()),
            ],
            options={
                'db_table': 'administradores_consorcio',
            },
        ),
    ]
